---
title: "imagery_awards"
format: html
---

Quick markdown file to count the number of imagery awards. For now I won't consider the "Most Photogenic" award from early FRC.

```{r}
library(devtools)
load_all()
awards <- readRDS("../data/awards/all_team_awards.rds")

count_imagery <- function(team_awards){
    if (ncol(team_awards) == 0) return(0)
    return(length(grep("Imagery", team_awards$name)))
}

img_count <- sort(sapply(awards, count_imagery), decreasing = TRUE)
img <- data.frame(team = names(img_count), imagery_awards = img_count)

write_csv(img, file = "../data/awards/imagery_award_counts.csv")

library(pander)

pander(table(img_count), 
       caption = "Imagery Award Counts (via TBA API)")

hist(img_count)
hist(img_count[img_count != 0])
```

# Rewriting for Impact

```{r}
library(devtools)
load_all()
awards <- readRDS("../data/awards/all_team_awards.rds")

count_impact <- function(team_awards){
    if (ncol(team_awards) == 0) return(0)
    return(length(grep("(Impact|Chairman's)", team_awards$name)))
}

impact_count <- sort(sapply(awards, count_impact), decreasing = TRUE)
impact <- data.frame(team = names(impact_count), impact_awards = impact_count)

library(pander)

pander(table(impact_count), 
       caption = "Impact Award Counts (via TBA API)")

# fields - "state_prov", "city", "country"
get_location <- function(team_id){
    obj <- team(team_id)
    paste(obj[["city"]], obj[["state_prov"]], obj[["country"]], sep = "#")
}

impact$location <- sapply(impact$team, get_location)
```

