---
title: "Rookie All-Star Performance & Sustainability"
format: html
---

```{r setup}
# loading the scoutR library: 
# https://github.com/GKrotkov/scoutR
library(devtools); load_all()
```

# Data Collection

```{r data-performance}
# list of every FRC team and their awards history
all_team_awards <- readRDS("../data/awards/all_team_awards.rds")

extract_cols <- function(team){
    if (nrow(team) == 0) return(
        data.frame(
            ras_year = NA, first_impact = NA, n_impacts = 0, first_ei = NA,
            n_eis = 0
        )
    )
    return(data.frame(
        ras_year = team$year[team$award_type == 10][1], 
        first_impact = team$year[team$award_type == 0][1],
        n_impacts = sum(team$award_type == 0),
        first_ei = team$year[team$award_type == 9][1],
        n_eis = sum(team$award_type == 9)
    ))
}

df <- lapply(all_team_awards, extract_cols)
tmp <- names(df)
df <- Reduce(rbind, df)
df$id <- tmp
rm(tmp)

ras <- df[!is.na(df$ras_year), ]
ras$yrs_to_impact <- ras$first_impact - ras$ras_year
ras$yrs_to_ei <- ras$first_ei - ras$ras_year
```

```{r data-sustainability}
# want each team's rookie year, number of (consecutive) years competed, 
# last year of competition
all_team_awards <- list()
all_teams <- c()
# teams are paginated in 500s, so pages = 20 goes up to team 9999
pages <- 30

# seq_len(pages) - 1 accounts for TBA's 0-indexing
for (i in (seq_len(pages) - 1)){
    all_teams <- c(all_teams, teams(i, keys = TRUE))
}

null_to_na <- function(v){
    if(is.null(v)) return(NA)
    return(v)
}

# I'm not super happy with consecutive seasons as a metric of sustainability, 
# because teams can take a break and come back. But it'll do for a first
# approximation
sustainability_cols <- function(id){
    team <- team(id)
    participation <- team_participation_years(id)
    return(data.frame(
        rookie_yr = null_to_na(team$rookie_year), 
        last_year = null_to_na(tail(participation, 1)),
        n_seasons = length(participation), 
        consecutive_seasons = 
            null_to_na(rle(diff(participation) == 1)$lengths[1])
    ))
}

df2 <- lapply(all_teams, sustainability_cols)
df2 <- Reduce(rbind, df2)
df2$id <- all_teams

```

# Reporting

```{r}
cat(nrow(ras), "unique RAS teams, with", sum(ras$n_impacts > 0), 
    "unique RAS teams winning", sum(ras$n_impacts, na.rm = TRUE), 
    "Impact awards.\n")
cat(nrow(df), "unique overall teams, with", sum(df$n_impacts > 0), 
    "unique teams winning", sum(df$n_impacts, na.rm = TRUE), 
    "Impact awards.\n")
hist(ras$yrs_to_impact, 
     main = "Years between RAS and Impact", xlab = "Years", ylab = "# of Teams")
hist(ras$yrs_to_ei, 
     main = "Years between RAS and EI", xlab = "Years", ylab = "# of Teams")
```

