---
title: "TA Hexafecta"
author: "Gabriel Krotkov"
date: "2024-04-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(devtools)
load_all()
```

```{r}
team_attributes_hexafecta <- function(id){
    awards <- team_awards(id)
    if (nrow(awards) == 0){
        return(FALSE)
    }
    unq <- unique(awards$name)
    return(
        (length(grep("Engineering Inspiration", unq)) > 0) & 
        (length(grep("(Gracious Professionalism|Sportsmanship)", unq)) > 0) &
        (length(grep("(Most Photogenic|Imagery)", unq)) > 0) &
        (length(grep("Team Spirit", unq)) > 0) & 
        (length(grep("(Judges|Judge's|Judges')", unq)) > 0) & 
        (length(grep("(Sustainability|Entrepreneurship)", unq)) > 0)
    )
}

all_teams <- c()

pages <- 0:19

for (i in pages){
    all_teams <- c(all_teams, teams(i, keys = TRUE))
}

data <- data.frame(team = all_teams)
data$ta_hexafecta <- apply(data, 1, team_attributes_hexafecta)
save(data, file = "../data/ta_hexafecta.rda")
```

```{r}
ta_hexafecta_teams <- data$team[data$ta_hexafecta]
```

```{r all-team-awards}
# THIS CODE CHUNCK MAKES VERY MANY CALLS TO THE TBA API
# SET ASIDE TIME TO LET IT RUN
all_team_awards <- list()

pages <- 0:19

for (i in pages){
    all_teams <- c(all_teams, teams(i, keys = TRUE))
}

for (i in seq_along(all_teams)){
    all_team_awards[[all_teams[i]]] <- team_awards(all_teams[i])
}

saveRDS(all_team_awards, file = "data/all_team_awards.rds")
```

@TODO debug - what was the "Autodesk Excellence in Engineering Creativity and Communications Award"? This causes a bug in my creativity award matching.

@TODO need some way to filter out offseasons rather than doing this on a per-award basis

@TODO need to reformat the code to make it readable

@TODO why is `modern_awards` a dataframe of dataframes?

```{r modern-awards}
unique_awards <- function(team_awards){
    if (nrow(team_awards) == 0){
        return(c())
    }
    return(unique(team_awards$name))
}

all_team_awards <- readRDS("../data/all_team_awards.rds")

team_unique_awards <- unlist(sapply(all_team_awards, unique_awards))
all_unique_awards <- unique(team_unique_awards)

count_modern_awards <- function(team_award_history){
    if (nrow(team_award_history) == 0){
        return(data.frame(
            impact = 0, ei = 0, ras = 0, autonomous = 0, creativity = 0, 
            eng_excellence = 0, gp = 0, imagery = 0, industrial_design = 0, 
            innovation_control = 0, quality = 0, judges = 0, rookie_insp = 0, 
            team_spirit = 0, sustainability = 0)
        )
    }
    award_names <- team_award_history$name
    result <- data.frame(
        impact = length(grep("(Impact|Chairman\'s)", award_names, ignore.case = TRUE)), 
        ei = length(grep("Engineering Inspiration", award_names, ignore.case = TRUE)), 
        ras = length(grep("(Rookie All-Star|Rookie All Star)", award_names, ignore.case = TRUE)), 
        autonomous = length(grep("Autonomous Award", award_names, ignore.case = TRUE)), 
        creativity = length(grep("Creativity", award_names, ignore.case = TRUE)), 
        eng_excellence = length(grep("(Engineering Excellence|Excellence in Engineering)", award_names, ignore.case = TRUE)), 
        gp = length(grep("(Gracious Professionalism|Sportsmanship)", award_names, ignore.case = TRUE)), 
        imagery = length(grep("(Imagery|Photogenic)", award_names, ignore.case = TRUE)), 
        industrial_design = length(grep("(Imagery|Photogenic)", award_names, ignore.case = TRUE)), 
        innovation_control = length(grep("(Control|Controls)", award_names, ignore.case = TRUE)), 
        quality = length(grep("Quality", award_names, ignore.case = TRUE)), 
        judges = length(grep("(Judges|Judge's|Judges')", award_names, ignore.case = TRUE)), 
        rookie_insp = length(grep("Rookie Inspiration", award_names, ignore.case = TRUE)), 
        team_spirit = length(grep("Spirit", award_names, ignore.case = TRUE)), 
        sustainability = length(grep("(Sustainability|Entrepreneurship)", award_names, ignore.case = TRUE))
    )
    return(result)
}

modern_awards <- data.frame(t(sapply(all_team_awards, count_modern_awards)))
```

