# data documentation file

#' District Qualification Data
#'
#' A list of qualification data from every district played between 2009 and
#' 2024. Every item in the list is a dataframe, and each dataframe has at least
#' the columns "red1", "red2", "red3", "blue1", "blue2", "blue3", "red_score",
#' and "blue_score". Generated by scripts/get_district_quals.R
#' @source thebluealliance.com
"dquals24"

#' Stepwise-Optimized OPR Weights
#'
#' Linear Regression weights optimized stepwise as outlined by Girls of Steel
#' in "Clutch Matches are in the Middle"
#'
#' @source "Clutch Matches are in the Middle, by Girls of Steel"
"w_stepwise"

#' All Team Awards
#'
#' List of all team official award histories as of the 2024 season
#' @source thebluealliance.com
"awards24"

#' Team Attributes Hexafecta
#'
#' DF noting whether each team has achieved the Team Attributes Hexafecta
#' as of 2024.
#' @source thebluealliance.com
"ta_hexafecta24"

#' Teams by Year
#'
#' Indicates each team-year competed (as of 2024)
"teams_yearly"
