# data documentation file

#' District Qualification Data
#'
#' A list of qualification data from every district played between 2009 and
#' 2024. Every item in the list is a dataframe, and each dataframe has at least
#' the columns "red1", "red2", "red3", "blue1", "blue2", "blue3", "red_score",
#' and "blue_score". Generated by scripts/get_district_quals.R
#' @source thebluealliance.com
"dquals24"

#' Stepwise-Optimized OPR Weights
#'
#' Linear Regression weights optimized stepwise as outlined by Girls of Steel
#' in "Clutch Matches are in the Middle"
#'
#' @source "Clutch Matches are in the Middle, by Girls of Steel"
"w_stepwise"

#' All Team Awards
#'
#' List of all team official award histories as of the 2024 season
#' @source thebluealliance.com
"awards24"

#' Team Attributes Hexafecta
#'
#' DF noting whether each team has achieved the Team Attributes Hexafecta
#' as of 2024.
#' @source thebluealliance.com
"ta_hexafecta24"

#' Teams by Year
#'
#' Indicates each team-year competed (as of 2024)
"teams_yearly"

#' OPR Swing data (2005 - 2025)
#'
#' "mean_diff" represents the mean change in standardized OPR coefficients
#' (mean across all teams at the event) after the corresponding match
#' "ppt" (plays per team) is the number of match plays the event has had,
#' divided by the number of teams at the event. So for example after 2025mdsev
#' ran match 13, there had been (13 * 6 = ) 78 "plays", across 28 teams at the
#' event, for about 2.79 ppt.
#' @source thebluealliance.com
"opr_swings"
